"""Whitepaper benchmark: Weft vs JPEG/WebP/PNG on the committed corpus.

Produces a reproducible CSV + summary table used in the Weft whitepaper.
For each corpus fixture we compute:

1. Weft bytes + PSNR at the default quality setting (auto_select, q=75)
2. For JPEG and WebP (lossy), the lowest quality level where the output
   size ≤ Weft bytes — this is the iso-bytes comparison (what PSNR do
   other codecs give for the same byte budget?)
3. PNG lossless bytes + PSNR (PSNR = ∞ for lossless; reported as 99.99)
4. WebP lossless bytes + PSNR

Output:
- CSV at samples/runs/whitepaper-bench/results.csv
- Summary table printed to stdout (Markdown-compatible)
- Per-fixture PSNR-vs-bytes figures (if matplotlib is available)

Usage:
    python scripts/whitepaper_bench.py

To include fixtures outside the committed corpus, pass a directory:
    python scripts/whitepaper_bench.py --corpus samples/inputs_extra/

The committed corpus is 14 fixtures spanning smooth gradients, pixel
art, diagrams, synthetic photos, and hard-edge content. All fixtures
are deterministic (generated by samples/inputs/_generate.py), so the
benchmark is fully reproducible from the repo alone — no external
datasets required.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import os
import sys
import time
from io import BytesIO

import numpy as np
from PIL import Image

# Make the weft package importable from a source checkout.
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from weft.api import encode_image  # noqa: E402
from weft.decoder import decode_to_array  # noqa: E402
from weft.image_io import linear_to_srgb  # noqa: E402
from weft.types import EncodeConfig  # noqa: E402


DEFAULT_CORPUS = [
    "samples/inputs/hard-edges.png",
    "samples/inputs/synth-chart.png",
    "samples/inputs/synth-diagram.png",
    "samples/inputs/synth-icons.png",
    "samples/inputs/synth-mandelbrot.png",
    "samples/inputs/synth-noise-texture.png",
    "samples/inputs/synth-photo-landscape.png",
    "samples/inputs/synth-photo-natural.png",
    "samples/inputs/synth-pixel-sprite.png",
    "samples/inputs/synth-region-map.png",
    "samples/inputs/synth-shapes.png",
    "samples/inputs/synth-smooth-gradient.png",
    "samples/inputs/synth-terminal.png",
    "samples/inputs/synthetic-render-1024.png",
]

DEFAULT_WEFT_QUALITY = 75


def psnr(a: np.ndarray, b: np.ndarray) -> float:
    """PSNR in dB over sRGB uint8 arrays."""
    a = a.astype(np.float64) / 255.0
    b = b.astype(np.float64) / 255.0
    mse = float(np.mean((a - b) ** 2))
    if mse <= 1e-12:
        return 99.99  # cap for display; lossless
    return 10.0 * math.log10(1.0 / mse)


def encode_weft_bytes_psnr(src_path: str, out_path: str, quality: int) -> tuple[int, float, str]:
    """Encode with Weft auto-select; return (bytes, PSNR vs source, variant)."""
    cfg = EncodeConfig(
        quality=quality,
        feature_flags={"auto_select": True},
        verify_drift_threshold_db=999.0,
    )
    rep = encode_image(src_path, out_path, cfg)
    variant = rep.metadata.get("auto_selected_variant", "?")

    # Decode back to compare against source (sRGB).
    decoded_linear = decode_to_array(out_path)
    decoded_srgb = (np.clip(linear_to_srgb(decoded_linear), 0.0, 1.0) * 255.0).astype(np.uint8)
    source = np.asarray(Image.open(src_path).convert("RGB"))
    # Dimensions may differ if encode_scale<1 was used; defensive.
    if decoded_srgb.shape != source.shape:
        source = np.asarray(
            Image.open(src_path).convert("RGB").resize(
                (decoded_srgb.shape[1], decoded_srgb.shape[0]), Image.LANCZOS
            )
        )
    return rep.bytes_written, psnr(source, decoded_srgb), variant


def encode_iso_bytes_lossy(src_img: Image.Image, fmt: str, target_bytes: int,
                            source_arr: np.ndarray) -> tuple[int, float, int]:
    """Find the highest quality for ``fmt`` (JPEG/WEBP) whose encoded
    size ≤ ``target_bytes``. Returns (bytes, PSNR vs source, quality_used)."""
    kwargs = {"JPEG": {"optimize": True}, "WEBP": {"method": 6}}[fmt]
    best = None
    # Binary search on quality 1..100
    lo, hi = 1, 100
    while lo <= hi:
        mid = (lo + hi) // 2
        buf = BytesIO()
        src_img.save(buf, fmt, quality=mid, **kwargs)
        b = buf.getvalue()
        if len(b) <= target_bytes:
            # fits; try higher quality
            decoded = np.asarray(Image.open(BytesIO(b)).convert("RGB"))
            p = psnr(source_arr, decoded)
            best = (len(b), p, mid)
            lo = mid + 1
        else:
            hi = mid - 1
    if best is None:
        # Even quality=1 overshot; return quality=1 numbers with overshoot flag.
        buf = BytesIO()
        src_img.save(buf, fmt, quality=1, **kwargs)
        b = buf.getvalue()
        decoded = np.asarray(Image.open(BytesIO(b)).convert("RGB"))
        return len(b), psnr(source_arr, decoded), 1
    return best


def encode_png_lossless(src_img: Image.Image) -> int:
    buf = BytesIO()
    src_img.save(buf, "PNG", optimize=True)
    return len(buf.getvalue())


def encode_webp_lossless(src_img: Image.Image) -> int:
    buf = BytesIO()
    src_img.save(buf, "WEBP", lossless=True, quality=100, method=6)
    return len(buf.getvalue())


def run(corpus: list[str], out_dir: str, weft_quality: int) -> None:
    os.makedirs(out_dir, exist_ok=True)
    results = []
    variants_seen: dict[str, int] = {}

    header = (
        f"{'fixture':<28} {'Weft KB':>8} {'Weft dB':>8}  "
        f"{'JPEG dB':>8} {'WebP dB':>8}  {'PNG KB':>8} {'WebPL KB':>8}  variant"
    )
    print(header)
    print("-" * len(header))

    for src in corpus:
        if not os.path.exists(src):
            print(f"  SKIP {src}")
            continue
        name = os.path.splitext(os.path.basename(src))[0]

        src_img = Image.open(src).convert("RGB")
        source_arr = np.asarray(src_img)

        out_weft = os.path.join(out_dir, f"{name}.weft")
        t0 = time.perf_counter()
        weft_bytes, weft_psnr, variant = encode_weft_bytes_psnr(src, out_weft, weft_quality)
        weft_encode_ms = (time.perf_counter() - t0) * 1000.0
        variants_seen[variant] = variants_seen.get(variant, 0) + 1

        jpeg_bytes, jpeg_psnr, jpeg_q = encode_iso_bytes_lossy(src_img, "JPEG", weft_bytes, source_arr)
        webp_bytes, webp_psnr, webp_q = encode_iso_bytes_lossy(src_img, "WEBP", weft_bytes, source_arr)

        png_bytes = encode_png_lossless(src_img)
        webpl_bytes = encode_webp_lossless(src_img)

        row = {
            "fixture": name,
            "width": source_arr.shape[1],
            "height": source_arr.shape[0],
            "weft_bytes": weft_bytes,
            "weft_psnr_db": round(weft_psnr, 3),
            "weft_variant": variant,
            "weft_encode_ms": round(weft_encode_ms, 1),
            "jpeg_bytes_iso": jpeg_bytes,
            "jpeg_psnr_iso_db": round(jpeg_psnr, 3),
            "jpeg_quality_iso": jpeg_q,
            "webp_bytes_iso": webp_bytes,
            "webp_psnr_iso_db": round(webp_psnr, 3),
            "webp_quality_iso": webp_q,
            "png_bytes": png_bytes,
            "webp_lossless_bytes": webpl_bytes,
        }
        results.append(row)

        print(
            f"{name:<28} {weft_bytes/1024:>8.1f} {weft_psnr:>8.2f}  "
            f"{jpeg_psnr:>8.2f} {webp_psnr:>8.2f}  "
            f"{png_bytes/1024:>8.1f} {webpl_bytes/1024:>8.1f}  {variant}"
        )

    # Aggregates
    n = len(results)
    if n == 0:
        print("\n(no fixtures processed)")
        return
    tot_weft = sum(r["weft_bytes"] for r in results)
    tot_jpeg = sum(r["jpeg_bytes_iso"] for r in results)
    tot_webp = sum(r["webp_bytes_iso"] for r in results)
    tot_png = sum(r["png_bytes"] for r in results)
    tot_webpl = sum(r["webp_lossless_bytes"] for r in results)
    avg_weft_psnr = sum(r["weft_psnr_db"] for r in results) / n
    avg_jpeg_psnr = sum(r["jpeg_psnr_iso_db"] for r in results) / n
    avg_webp_psnr = sum(r["webp_psnr_iso_db"] for r in results) / n

    weft_wins_vs_jpeg = sum(
        1 for r in results if r["weft_psnr_db"] > r["jpeg_psnr_iso_db"]
    )
    weft_wins_vs_webp = sum(
        1 for r in results if r["weft_psnr_db"] > r["webp_psnr_iso_db"]
    )

    print("-" * len(header))
    print(
        f"{'AGGREGATE':<28} {tot_weft/1024:>8.1f} {avg_weft_psnr:>8.2f}  "
        f"{avg_jpeg_psnr:>8.2f} {avg_webp_psnr:>8.2f}  "
        f"{tot_png/1024:>8.1f} {tot_webpl/1024:>8.1f}"
    )
    print()
    print(f"Fixtures: {n}")
    print(f"Iso-byte wins (Weft PSNR > alternative):")
    print(f"  Weft vs JPEG:  {weft_wins_vs_jpeg}/{n}  (avg delta {avg_weft_psnr - avg_jpeg_psnr:+.2f} dB)")
    print(f"  Weft vs WebP:  {weft_wins_vs_webp}/{n}  (avg delta {avg_weft_psnr - avg_webp_psnr:+.2f} dB)")
    print()
    print("Variants chosen by auto-select:")
    for v, c in sorted(variants_seen.items(), key=lambda x: -x[1]):
        print(f"  {v}: {c}")

    # Write CSV
    csv_path = os.path.join(out_dir, "results.csv")
    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(results[0].keys()))
        writer.writeheader()
        writer.writerows(results)
    print(f"\nCSV: {csv_path}")

    # Write JSON summary for downstream consumption
    summary = {
        "weft_quality": weft_quality,
        "fixture_count": n,
        "aggregate": {
            "weft_total_bytes": tot_weft,
            "jpeg_total_bytes_iso": tot_jpeg,
            "webp_total_bytes_iso": tot_webp,
            "png_total_bytes": tot_png,
            "webp_lossless_total_bytes": tot_webpl,
            "weft_avg_psnr_db": round(avg_weft_psnr, 3),
            "jpeg_avg_psnr_iso_db": round(avg_jpeg_psnr, 3),
            "webp_avg_psnr_iso_db": round(avg_webp_psnr, 3),
            "weft_vs_jpeg_avg_delta_db": round(avg_weft_psnr - avg_jpeg_psnr, 3),
            "weft_vs_webp_avg_delta_db": round(avg_weft_psnr - avg_webp_psnr, 3),
            "weft_iso_wins_vs_jpeg": weft_wins_vs_jpeg,
            "weft_iso_wins_vs_webp": weft_wins_vs_webp,
        },
        "variants": variants_seen,
        "per_fixture": results,
    }
    summary_path = os.path.join(out_dir, "summary.json")
    with open(summary_path, "w") as f:
        json.dump(summary, f, indent=2)
    print(f"JSON: {summary_path}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--corpus-dir", help="Override corpus directory (default: committed samples/inputs)")
    ap.add_argument("--out", default="samples/runs/whitepaper-bench", help="Output directory")
    ap.add_argument("--quality", type=int, default=DEFAULT_WEFT_QUALITY, help="Weft quality (default 75)")
    args = ap.parse_args()

    if args.corpus_dir:
        files = sorted(
            os.path.join(args.corpus_dir, f)
            for f in os.listdir(args.corpus_dir)
            if f.lower().endswith((".png", ".jpg", ".jpeg"))
        )
    else:
        files = DEFAULT_CORPUS

    run(files, args.out, args.quality)
